// <auto-generated />
namespace Flex_SGM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddNivelRiesgoToPcr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNivelRiesgoToPcr));
        
        string IMigrationMetadata.Id
        {
            get { return "202410282039218_AddNivelRiesgoToPcr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
