// <auto-generated />
namespace Flex_SGM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddMsgToFeasibilitySigns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMsgToFeasibilitySigns));
        
        string IMigrationMetadata.Id
        {
            get { return "202410311319094_AddMsgToFeasibilitySigns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
